/*
 * This file is generated by jOOQ.
 */
package com.lickhunter.spotbot.entities;


import com.lickhunter.spotbot.entities.tables.Account;
import com.lickhunter.spotbot.entities.tables.Symbol;
import com.lickhunter.spotbot.entities.tables.records.AccountRecord;
import com.lickhunter.spotbot.entities.tables.records.SymbolRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> PK_ACCOUNT = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("PK_ACCOUNT"), new TableField[] { Account.ACCOUNT.ID }, true);
    public static final UniqueKey<SymbolRecord> PK_SYMBOL = Internal.createUniqueKey(Symbol.SYMBOL, DSL.name("PK_SYMBOL"), new TableField[] { Symbol.SYMBOL.SYMBOL_ }, true);
}
