/*
 * This file is generated by jOOQ.
 */
package com.lickhunter.spotbot.entities;


import com.lickhunter.spotbot.entities.tables.Account;
import com.lickhunter.spotbot.entities.tables.Symbol;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>SYMBOL</code>.
     */
    public static final Symbol SYMBOL = Symbol.SYMBOL;
}
